// <auto-generated />
using System;
using Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Admin.AdminModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Companies.CompanyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_contact");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_contact");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("companies", null, t =>
                        {
                            t.HasCheckConstraint("CK_email_contact_format", "email_contact ~ '^[^@]+@[^@]+\\.[^@]+$'");

                            t.HasCheckConstraint("CK_name_length", "LENGTH(name) >=3 AND LENGTH(name) <= 15");

                            t.HasCheckConstraint("CK_phone_contact_length", "LENGTH(phone_contact) = 11");

                            t.HasCheckConstraint("CK_phone_contact_text_digits", "phone_contact ~ '^[0-9]*$'");

                            t.HasCheckConstraint("CK_updatedat_more_createdat", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Domain.Models.Customer.CustomerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Rating")
                        .HasColumnType("numeric(2, 1)")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_rating_range", "rating BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("Domain.Models.Profile.ProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_age_range", "age BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_name_length", "LENGTH(name) >=3 AND LENGTH(name) <= 15");

                            t.HasCheckConstraint("CK_patronymic_length", "LENGTH(patronymic) >=3 AND LENGTH(patronymic) <= 25");

                            t.HasCheckConstraint("CK_surname_length", "LENGTH(surname) >=3 AND LENGTH(surname) <= 25");
                        });
                });

            modelBuilder.Entity("Domain.Models.Role.RoleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Seller.SellerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_contact");

                    b.Property<string>("PhoneContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_contact");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("sellers", null, t =>
                        {
                            t.HasCheckConstraint("CK_email_contact_format", "email_contact ~ '^[^@]+@[^@]+\\.[^@]+$'");

                            t.HasCheckConstraint("CK_phone_contact_text_digits", "phone_contact ~ '^[0-9]*$'");
                        });
                });

            modelBuilder.Entity("Domain.Models.Shop.ShopModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Rating")
                        .HasColumnType("numeric(2, 1)")
                        .HasColumnName("rating");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("shops", null, t =>
                        {
                            t.HasCheckConstraint("CK_description_length", "LENGTH(description) >=0 AND LENGTH(description) <= 300");

                            t.HasCheckConstraint("CK_name_length", "LENGTH(name) >=3 AND LENGTH(name) <= 30");

                            t.HasCheckConstraint("CK_rating_range", "rating BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_updatedat_more_createdat", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Domain.Models.User.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Login");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_email_format", "email ~ '^[^@]+@[^@]+\\.[^@]+$'");

                            t.HasCheckConstraint("CK_login_length", "LENGTH(login) >=5 AND LENGTH(login) <= 20");

                            t.HasCheckConstraint("CK_phone_number_length", "LENGTH(phone_number) = 11");

                            t.HasCheckConstraint("CK_phone_number_text_digits", "phone_number ~ '^[0-9]*$'");

                            t.HasCheckConstraint("CK_updatedat_more_createdat", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Domain.Models.UserRole.UserRoleModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("users_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Admin.AdminModel", b =>
                {
                    b.HasOne("Domain.Models.User.UserModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Admin.AdminModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Customer.CustomerModel", b =>
                {
                    b.HasOne("Domain.Models.User.UserModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Customer.CustomerModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Profile.ProfileModel", b =>
                {
                    b.HasOne("Domain.Models.User.UserModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Profile.ProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Seller.SellerModel", b =>
                {
                    b.HasOne("Domain.Models.Companies.CompanyModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Seller.SellerModel", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.Shop.ShopModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Seller.SellerModel", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.User.UserModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Seller.SellerModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Shop.ShopModel", b =>
                {
                    b.HasOne("Domain.Models.Seller.SellerModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Shop.ShopModel", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.UserRole.UserRoleModel", b =>
                {
                    b.HasOne("Domain.Models.Role.RoleModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.UserRole.UserRoleModel", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User.UserModel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.UserRole.UserRoleModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
