<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="BCrypt.Net-Next" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="PlopyBlopy.FluentResults.Errors" />
		<PackageReference Include="PlopyBlopy.MediatoR.Alternative.Lite" />
		<PackageReference Include="Scrutor" />
		<PackageReference Include="FluentValidation" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="UnitTests" />
		<InternalsVisibleTo Include="IntegrationTests" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Abstractions\" />
	  <Folder Include="Queries\" />
	</ItemGroup>
</Project>
