<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\API\API.csproj" />
		<ProjectReference Include="..\..\src\Application\Application.csproj" />
		<ProjectReference Include="..\..\src\Domain\Domain.csproj" />
		<ProjectReference Include="..\..\src\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\..\src\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Data\" />
	  <Folder Include="Helpers\" />
	  <Folder Include="Tests\ComponentTests\Endpoints\" />
	  <Folder Include="Tests\FunctionalTests\Endpoints\" />
	</ItemGroup>
</Project>
