<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="AutoMapper" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Application">
      <HintPath>..\Application\bin\Debug\net9.0\Application.dll</HintPath>
    </Reference>
    <Reference Include="Web.Api">
      <HintPath>..\Web.Api\bin\Debug\net9.0\Web.Api.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
